#this scenario will be executed in case of PR approve
name: pr approve deploy ochestration logic

#depends on the target branch one of the following scenarios will be executed:
on:
  pull_request_review:
    types: [submitted]



jobs:

  logger:
    runs-on: ubuntu-latest
    steps:
      - name: logger
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.head.ref }}
          TEST=${{ github.event.pull_request.head.ref }}
          echo $TEST

  dev_pr_munits:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'dev'
    steps:
      - name: test
        run:
          echo $TEST

      - name: test2
        uses: ./.github/workflows/PR_approve_deploy_dev.yml

  qa_pr_munits:
    if: github.event.pull_request.head.ref == 'qa'
    uses: ./.github/workflows/PR_approve_deploy_dev.yml

  uat_pr_munits:
    if: ${{ github.event.pull_request.head.ref }} == 'uat'
    uses: ./.github/workflows/PR_approve_deploy_dev.yml

  staging_pr_munits:
    if: ${{ github.event.pull_request.head.ref }} == 'staging'
    uses: ./.github/workflows/PR_approve_deploy_dev.yml

  prod_pr_munits:
    if: ${{ github.event.pull_request.head.ref }} == 'prod'
    uses: ./.github/workflows/PR_approve_deploy_dev.yml
 