#this scenario will be executed in case of PR approve
name: pr approve deploy ochestration logic

#depends on the target branch one of the following scenarios will be executed:
on:
  pull_request_review:
    types: [submitted]



jobs:

  logger:
    runs-on: ubuntu-latest
    steps:
      - name: logger
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.head.ref }}



